# Footnotes and citations 

```{r}
library(SpatialEpi)
library(sp)
library(leaflet)
library(cmdstanr)
library(posterior)
library(bayesplot)
source("../files/utils.R")
source("../files/data/scotland_data.R")


options(mc.cores = parallel::detectCores())
```

## Footnotes

```{r}
y    = data$y;
x    = 0.1 * data$x;
E    = data$E
logE = log(E);

nbs     = mungeCARdata4stan(data$adj, data$num)
N       = nbs$N
N_edges = nbs$N_edges
node1   = nbs$node1
node2   = nbs$node2

D <- matrix(0, nrow = N_edges, ncol = N)
for(i in 1:N_edges){
    D[i,node1[i]] <- -1
    D[i,node2[i]] <- 1}
```



```{r}
B    <- cbind(rep(1,N), x)
dat1 <- list(N            = N,
             N_edges      = N_edges,
             N_covariates = 2,
             O            = y,
             logE         = logE,
             B            = B,
             D            = as.matrix(D),
             thetaetas    = 5,
             thetamus     = 4)
```

```{r}
model_stan_Gauss <- cmdstan_model('../files/stan/GaussPoissonCAR.stan')
fit_Gauss <- model_stan_Gauss$sample(data = dat1, 
                                     chains = 2, 
                                     iter_warmup = 5000, 
                                     iter_sampling = 2000,
                                     adapt_delta = 0.97,
                                     max_treedepth = 20)

fit_Gauss$save_object("fit_scotland_Gauss.rds")
```

```{r}
model_stan_NIG <- cmdstan_model('../files/stan/NIGPoissonCAR.stan')
fit_NIG <- model_stan_NIG$sample(data = dat1, 
                                 chains = 2, 
                                 iter_warmup = 5000, 
                                 iter_sampling = 2000,
                                 adapt_delta = 0.97,
                                 max_treedepth = 20)

fit_NIG$save_object("fit_scotland_NIG.rds")
```

```{r}
fit_Gauss <- readRDS("fit_scotland_Gauss.rds")
fit_NIG   <- readRDS("fit_scotland_NIG.rds")

mcmc_pairs(fit_Gauss$draws(c("beta[1]", "beta[2]", "sigma")),
           diag_fun="dens", off_diag_fun="hex")

mcmc_pairs(fit_NIG$draws(c("beta[1]", "beta[2]", "sigma","etas","mus")),
           diag_fun="dens", off_diag_fun="hex")
```

```{r}
X     <- as.matrix(as_draws_df(fit_NIG$draws("X")))[,1:N]
etas  <- as.matrix(as_draws_df(fit_NIG$draws("etas")))[,1]
mus   <- as.matrix(as_draws_df(fit_NIG$draws("mus")))[,1]
h     <- rep(1,N_edges)

V_post <- Vposterior(X, 0, D, etas, mus, h)
plot(colMeans(V_post))
```
maybe you need sigmas correction
RR you need to take exponential??

```{r}
data(scotland)
map <- scotland$spatial.polygon

RR       <- as_draws_df(fit_NIG$draws("RR"))[,1:N]
map$RR   <- colMeans(RR)
map$LL   <- apply(RR, 2, function(x) quantile(x,0.05))
map$UL   <- apply(RR, 2, function(x) quantile(x,0.95))


codes <- rgdal::make_EPSG()
codes[which(codes$code == "27700"), ]
proj4string(map) <- "+proj=tmerc +lat_0=49 +lon_0=-2
+k=0.9996012717 +x_0=400000 +y_0=-100000 +datum=OSGB36
+units=km +no_defs"
map <- spTransform(map, CRS("+proj=longlat +datum=WGS84 +no_defs"))

d <- scotland$data[,c("county.names", "cases", "expected", "AFF")]
names(d) <- c("county", "Y", "E", "AFF")
d$SIR <- d$Y / d$E
sapply(slot(map, "polygons"), function(x){slot(x, "ID")})
rownames(d) <- d$county
map <- SpatialPolygonsDataFrame(map, d, match.ID = TRUE)

labels <- sprintf("<strong> %s </strong> <br/>
  Observed: %s <br/> Expected: %s <br/>
  AFF: %s <br/> SIR: %s <br/> RR: %s (%s, %s)",
  map$county, y, round(E, 2),
  x, round(map$SIR, 2), round(map$RR, 2),
  round(map$LL, 2), round(map$UL, 2)) %>% lapply(htmltools::HTML)

pal <- colorNumeric(palette = "YlOrRd", domain = map$RR)
leaflet(map) %>%
  addProviderTiles(providers$Esri.WorldImagery) %>% 
  addPolygons(
    color = "grey", weight = 1, fillColor = ~ pal(RR),
    fillOpacity = 0.5,
    highlightOptions = highlightOptions(weight = 4),
    label = labels,
    labelOptions = labelOptions(
      style =
        list(
          "font-weight" = "normal",
          padding = "3px 8px"
        ),
      textsize = "15px", direction = "auto"
    )
  ) %>%
  addLegend(
    pal = pal, values = ~RR, opacity = 0.5, title = "RR",
    position = "bottomright"
  )

```